options:
  sonarr-user:
    type: string
    default: "sonarruser"
    description: "The user to install sonarr under"
  port:
    type: int
    default: 8989
    description: "Port for sonarr"
  restore-config:
    type: boolean
    default: False
    description: "Restore a previous configuration from resource"
  proxy-port:
    type: int
    default: 443
    description: "Port to request for reverse proxy access"
  proxy-domain:
    type: string
    default: "sonarr"
    description: "Subdomain to request from reverse proxy"
  proxy-url:
    type: string
    default: "/sonarr"
    description: 'Urlbase for revrse proxy, must start with a "/"'

