options:
  port:
    type: int
    default: 8989
    description: "Port for sonarr"
  restore-config:
    type: boolean
    default: False
    description: "Restore a previous configuration from resource"
  proxy-port:
    type: int
    default: 443
    description: "Port to request for reverse proxy access"
  proxy-domain:
    type: string
    default: "sonarr"
    description: "Subdomain to request from reverse proxy"
  proxy-url:
    type: string
    default: "/sonarr"
    description: 'Urlbase for revrse proxy, must start with a "/"'
  proxy-group:
    type: string
    default: "sonarr"
    description: "The name of the backend this charm will use, this should be unique for deployment/reverseproxy. Sonarr is not designed to be run in HA with multiple units grouped"

